project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    toc: true

website:
  title: "我的个人网站"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 关于我

